spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

#spring.application.name=blooms
#spring.main.web-application-type=servlet
#
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.toolbar=true
#
##spring.datasource.url=jdbc:h2:file:~/test2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
##spring.datasource.driver-class-name=org.h2.Driver
##spring.datasource.username=sa
##spring.datasource.password=
##
### JPA
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.format_sql=true
##spring.jpa.open-in-view=false
#
##spring.data.mongodb.uri=mongodb+srv://jackeyjazzbgp1234_db_user:AkqQko5t6eXihTja@cluster0.kc4exu8.mongodb.net/blooms_db?=Cluster0
##spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=blooms_db
#
#
## Swagger/OpenAPI
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.operationsSorter=method
