spring.application.name=blooms
spring.data.mongodb.database=blooms_db
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://blooms:AfIGvAnFQ7fecGSL@cluster0.kc4exu8.mongodb.net/blooms_db?appName=Cluster0}
spring.data.mongodb.auto-index-creation=true

