spring.application.name=blooms
spring.data.mongodb.database=blooms_db
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://jackeyjazzbgp1234_db_user:ZThZ7xCJfu8UJMR@cluster0.kc4exu8.mongodb.net/blooms_db?retryWrites=true&w=majority}
spring.data.mongodb.auto-index-creation=true
